# Generated by Django 2.2 on 2019-04-02 15:00

from django.db import migrations, models
#  мб все миграции схлопнуть в одну?

class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20190402_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tr_hash',
            field=models.UUIDField(default='16fd2706-8baf-433b-82eb-8c7fada847da'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
